version: '2'
services:
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    ports:
      - "8000:80"
  php:
    extends:
      file: docker-compose.base.yml
      service: php
    environment:
      APP_ENV: local
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    ports:
      - "33006:33006"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-app
      MYSQL_USER: app-user
      MYSQL_PASSWORD: app-pass
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
networks:
  ab-net:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"